<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Все производители");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"brands", 
	array(
		"COMPONENT_TEMPLATE" => "brands",
		"IBLOCK_TYPE" => "system",
		"IBLOCK_ID" => "#SYSTEM_BRANDS_IBLOCK_ID#",
		"NEWS_COUNT" => "20",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_THEME" => "default",
		"FILTER_SCROLL_PROPS" => array(
			0 => "BRAND_REF",
		),
		"FILTER_SEARCH_PROPS" => array(
			0 => "BRAND_REF",
		),
		"INSTANT_RELOAD" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"BRAND_PROP" => "BRAND_REF",
		"CATALOG_IBLOCK_TYPE" => "catalog",
		"CATALOG_IBLOCK_ID" => "#CATALOG_CATALOG_IBLOCK_ID#",
		"CATALOG_BRAND_PROP" => "BRAND_REF",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"LABEL_PROP" => array(
			0 => "NEWPRODUCT",
			1 => "SPECIALOFFER",
		),
		"CATALOG_PRICE_PROP" => "PRICE",
		"CATALOG_DISCOUNT_PROP" => "DISCOUNT",
		"CATALOG_CURRENCY_PROP" => "CURRENCY",
		"CATALOG_PRICE_DECIMALS" => "0",
		"SHOW_OLD_PRICE" => "Y",
		"CATALOG_ARTNUMBER_PROP" => "ARTNUMBER",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "#SITE_DIR#brands/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"BASKET_URL" => "#SITE_DIR##CART_PATH#",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"USE_COMPARE" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "Y",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"IS_USE_CART" => "Y",
		"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
		"USE_ENHANCED_ECOMMERCE" => "Y",
		"DATA_LAYER_NAME" => "dataLayer",
		"BRAND_PROPERTY" => "BRAND_REF",
		"USE_SORTER" => "Y",
		"SORTER_ACTION_PARAM_NAME" => "alfaction",
		"SORTER_ACTION_PARAM_VALUE" => "alfavalue",
		"SORTER_CHOSE_TEMPLATES_SHOW" => "Y",
		"SORTER_CNT_TEMPLATES" => "2",
		"SORTER_CNT_TEMPLATES_0" => "Плитка",
		"SORTER_CNT_TEMPLATES_NAME_0" => "vid-2",
		"SORTER_CNT_TEMPLATES_1" => "Список",
		"SORTER_CNT_TEMPLATES_NAME_1" => "vid-1",
		"SORTER_DEFAULT_TEMPLATE" => "",
		"SORTER_SORT_BY_SHOW" => "Y",
		"SORTER_SORT_BY_NAME" => array(
			0 => "sort",
			1 => "name",
			2 => "#SORTER_CATALOG_PRICE#",
			3 => "",
		),
		"SORTER_SORT_BY_DEFAULT" => "sort_asc",
		"SORTER_OUTPUT_OF_SHOW" => "Y",
		"SORTER_OUTPUT_OF" => array(
			0 => "",
			1 => "12",
			2 => "24",
			3 => "36",
			4 => "",
		),
		"SORTER_OUTPUT_OF_DEFAULT" => "12",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"LIST_PRODUCT_BLOCKS" => array(
			0 => "price",
			1 => "buttons",
			2 => "preview",
		),
		"LIST_PRODUCT_BLOCKS_ORDER" => "preview,props,price,buttons",
		"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"LIST_ENLARGE_PRODUCT" => "STRICT",
		"CATALOG_PROPERTY_CODE" => array(
			0 => "NEWPRODUCT",
			1 => "",
		),
		"LIST_TEMPLATE" => "master",
		"SORTER_TEMPLATE" => "master",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "BRAND_REF",
			1 => "",
		),
		"SHOW_DEACTIVATED" => "N",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "master",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Бренды",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"LAZY_LOAD" => "Y",
		"MESS_BTN_LAZY_LOAD" => "Показать ещё",
		"LOAD_ON_SCROLL" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SECTIONS_SHOW_SIDEBAR" => "Y",
		"LABEL_PROP_MOBILE" => array(
		),
		"LIST_LABEL_PROP_POSITION" => "bottom-left",
		"HIDE_NOT_AVAILABLE" => "N",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"SHOW_MAX_QUANTITY" => "N",
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"CONVERT_CURRENCY" => "N",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>